### ISSUE TITLE
I could draft a more comprehensive README file 🥺

### ISSUE THREAD

**Issue by Ehiane** [theblaisecode/Crave#1]
Hi! I've been seeing your progress from twitter and I love how dedicated you've been to this project. I would love to atleast, collaborate with you by improving your readme file and making it more comprehensive for people to read and understand, it would be a pleasure, if you could let me. 

Ehiane.

**Comment by theblaisecode** [comment]
Sure, collaboration is always welcome! Feel free to start working on the improvements.

**Comment by Ehiane** [comment]
Thank You!

**Comment by Ehiane** [comment]
# 🔗 ![logo](https://github.com/Ehiane/Crave/assets/79903725/2300d011-96e0-474f-8ec3-7098024449e7) [Crave](https://theblaisecode.github.io/Crave/index.html) - A fully responsive restaurant design

## Introduction
Experience a culinary symphony of flavor at Crave, where each dish is an artful masterpiece crafted with passion and precision. <br>From the first bite to the last, our menu is a symphony of taste sensations that will tantalize your taste buds and leave you craving for more.<br>
From the beloved Nigerian 5-star delicacy, [**`Beans and Dodo`**](https://theblaisecode.github.io/Crave/index.html#), to the aromatic and flavorful Indian[**` Rice and Curry`**](https://theblaisecode.github.io/Crave/index.html#) Delicacy, we've got what it takes to make your stomach satisfied.

## Demo
### Desktop view
<video src="https://github.com/Ehiane/Crave/assets/79903725/3e78df8a-e1a8-4835-a601-ce09e38e2135" controls autoplay width="100">
        <p>Your browser does not support this video</p>
    </video>

### Mobile view

https://github.com/Ehiane/Crave/assets/79903725/913c91be-e055-4bee-8781-755bf884578c







## Tech Stack
|                  |         |
|------------------| ------- |
|     HTML         |   <a href="https://developer.mozilla.org/en-US/docs/Web/HTML" target="_blank"><img align="center" src="https://raw.githubusercontent.com/devicons/devicon/master/icons/html5/html5-original.svg" alt="HTML" height="30" width="30" style="margin-right: 10px;" /></a>       |
|    CSS           |    <a href="https://developer.mozilla.org/en-US/docs/Web/CSS" target="_blank"><img align="center" src="https://raw.githubusercontent.com/devicons/devicon/master/icons/css3/css3-original.svg" alt="CSS" height="30" width="30" style="margin-right: 10px;" /></a>      |
|    JAVASCRIPT    |    <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript" target="_blank"><img align="center" src="https://raw.githubusercontent.com/devicons/devicon/master/icons/javascript/javascript-original.svg" alt="JavaScript" height="30" width="30" style="margin-right: 10px;" /></a>    |
|    Swipper JS    |     <a href="https://swiperjs.com/" target="_blank"><img align="center" src="https://github.com/Ehiane/Crave/assets/79903725/16596509-2f7f-4560-ac9b-b0e85ac7a1fc" alt="Swiper.js" height="30" width="30" style="margin-right: 10px;" /></a>   |


## Authors
|                     Author(s)                                     | Avatar | Contribution |
| ---------------------------------------------------------------| ----- | ------------ |
| <a href="https://github.com/theblaisecode">theblaisecode: </a> | <img align="center" src="https://github.com/Ehiane/Crave/assets/79903725/b071dab4-d2f0-455a-b81e-1df4cea14648" height="40" width="40"> | Website Development and Styling |
| <a href= "https://github.com/Ehiane" >Ehiane: </a>             | <img align="center" src="https://github.com/Ehiane/100_days_of_code_in_python-Projects/assets/79903725/55af3614-5f7d-4774-be46-e26a1d98f97d" height="40" width="40" /></a> | Readme Creation | 



## Socials 
<a href="https://twitter.com/theblaisecode" target="blank"><img align="center" src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/twitter.svg" alt="the_ehiane" height="30" width="40" /></a>
<a href="https://www.linkedin.com/in/theblaisecode" target="blank"><img align="center" src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/linked-in-alt.svg" alt="ehiane oigiagbe" height="30" width="40" />
